package com.lintu.demo.domain;

import java.util.Date;

public class Leave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.l_start
     *
     * @mbggenerated
     */
    private Date lStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.l_end
     *
     * @mbggenerated
     */
    private Date lEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.time
     *
     * @mbggenerated
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.l_type
     *
     * @mbggenerated
     */
    private Integer lType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_leave.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.id
     *
     * @return the value of l_leave.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.id
     *
     * @param id the value for l_leave.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.l_start
     *
     * @return the value of l_leave.l_start
     *
     * @mbggenerated
     */
    public Date getlStart() {
        return lStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.l_start
     *
     * @param lStart the value for l_leave.l_start
     *
     * @mbggenerated
     */
    public void setlStart(Date lStart) {
        this.lStart = lStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.l_end
     *
     * @return the value of l_leave.l_end
     *
     * @mbggenerated
     */
    public Date getlEnd() {
        return lEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.l_end
     *
     * @param lEnd the value for l_leave.l_end
     *
     * @mbggenerated
     */
    public void setlEnd(Date lEnd) {
        this.lEnd = lEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.time
     *
     * @return the value of l_leave.time
     *
     * @mbggenerated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.time
     *
     * @param time the value for l_leave.time
     *
     * @mbggenerated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.l_type
     *
     * @return the value of l_leave.l_type
     *
     * @mbggenerated
     */
    public Integer getlType() {
        return lType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.l_type
     *
     * @param lType the value for l_leave.l_type
     *
     * @mbggenerated
     */
    public void setlType(Integer lType) {
        this.lType = lType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.status
     *
     * @return the value of l_leave.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.status
     *
     * @param status the value for l_leave.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_leave.user_id
     *
     * @return the value of l_leave.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_leave.user_id
     *
     * @param userId the value for l_leave.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}