package com.lintu.demo.domain;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_action
     *
     * @mbggenerated
     */
    private String menuAction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_id
     *
     * @return the value of oa_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_id
     *
     * @param menuId the value for oa_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_name
     *
     * @return the value of oa_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_name
     *
     * @param menuName the value for oa_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.parentid
     *
     * @return the value of oa_menu.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.parentid
     *
     * @param parentid the value for oa_menu.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_action
     *
     * @return the value of oa_menu.menu_action
     *
     * @mbggenerated
     */
    public String getMenuAction() {
        return menuAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_action
     *
     * @param menuAction the value for oa_menu.menu_action
     *
     * @mbggenerated
     */
    public void setMenuAction(String menuAction) {
        this.menuAction = menuAction == null ? null : menuAction.trim();
    }
}