package com.lintu.demo.domain;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role_menu.role_menu_id
     *
     * @mbggenerated
     */
    private Integer roleMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role_menu.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_role_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role_menu.role_menu_id
     *
     * @return the value of oa_role_menu.role_menu_id
     *
     * @mbggenerated
     */
    public Integer getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role_menu.role_menu_id
     *
     * @param roleMenuId the value for oa_role_menu.role_menu_id
     *
     * @mbggenerated
     */
    public void setRoleMenuId(Integer roleMenuId) {
        this.roleMenuId = roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role_menu.role_id
     *
     * @return the value of oa_role_menu.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role_menu.role_id
     *
     * @param roleId the value for oa_role_menu.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_role_menu.menu_id
     *
     * @return the value of oa_role_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_role_menu.menu_id
     *
     * @param menuId the value for oa_role_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}