package com.lintu.demo.domain;

import java.util.Date;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.daterecord
     *
     * @mbggenerated
     */
    private Date daterecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.record1
     *
     * @mbggenerated
     */
    private String record1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.record2
     *
     * @mbggenerated
     */
    private String record2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.record3
     *
     * @mbggenerated
     */
    private String record3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.record4
     *
     * @mbggenerated
     */
    private String record4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.leave_q
     *
     * @mbggenerated
     */
    private String leaveQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.Late
     *
     * @mbggenerated
     */
    private String late;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.leave_early
     *
     * @mbggenerated
     */
    private String leaveEarly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.days_off
     *
     * @mbggenerated
     */
    private String daysOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.id
     *
     * @return the value of sign.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.id
     *
     * @param id the value for sign.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.daterecord
     *
     * @return the value of sign.daterecord
     *
     * @mbggenerated
     */
    public Date getDaterecord() {
        return daterecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.daterecord
     *
     * @param daterecord the value for sign.daterecord
     *
     * @mbggenerated
     */
    public void setDaterecord(Date daterecord) {
        this.daterecord = daterecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.record1
     *
     * @return the value of sign.record1
     *
     * @mbggenerated
     */
    public String getRecord1() {
        return record1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.record1
     *
     * @param record1 the value for sign.record1
     *
     * @mbggenerated
     */
    public void setRecord1(String record1) {
        this.record1 = record1 == null ? null : record1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.record2
     *
     * @return the value of sign.record2
     *
     * @mbggenerated
     */
    public String getRecord2() {
        return record2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.record2
     *
     * @param record2 the value for sign.record2
     *
     * @mbggenerated
     */
    public void setRecord2(String record2) {
        this.record2 = record2 == null ? null : record2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.record3
     *
     * @return the value of sign.record3
     *
     * @mbggenerated
     */
    public String getRecord3() {
        return record3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.record3
     *
     * @param record3 the value for sign.record3
     *
     * @mbggenerated
     */
    public void setRecord3(String record3) {
        this.record3 = record3 == null ? null : record3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.record4
     *
     * @return the value of sign.record4
     *
     * @mbggenerated
     */
    public String getRecord4() {
        return record4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.record4
     *
     * @param record4 the value for sign.record4
     *
     * @mbggenerated
     */
    public void setRecord4(String record4) {
        this.record4 = record4 == null ? null : record4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.leave_q
     *
     * @return the value of sign.leave_q
     *
     * @mbggenerated
     */
    public String getLeaveQ() {
        return leaveQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.leave_q
     *
     * @param leaveQ the value for sign.leave_q
     *
     * @mbggenerated
     */
    public void setLeaveQ(String leaveQ) {
        this.leaveQ = leaveQ == null ? null : leaveQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.Late
     *
     * @return the value of sign.Late
     *
     * @mbggenerated
     */
    public String getLate() {
        return late;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.Late
     *
     * @param late the value for sign.Late
     *
     * @mbggenerated
     */
    public void setLate(String late) {
        this.late = late == null ? null : late.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.leave_early
     *
     * @return the value of sign.leave_early
     *
     * @mbggenerated
     */
    public String getLeaveEarly() {
        return leaveEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.leave_early
     *
     * @param leaveEarly the value for sign.leave_early
     *
     * @mbggenerated
     */
    public void setLeaveEarly(String leaveEarly) {
        this.leaveEarly = leaveEarly == null ? null : leaveEarly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.days_off
     *
     * @return the value of sign.days_off
     *
     * @mbggenerated
     */
    public String getDaysOff() {
        return daysOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.days_off
     *
     * @param daysOff the value for sign.days_off
     *
     * @mbggenerated
     */
    public void setDaysOff(String daysOff) {
        this.daysOff = daysOff == null ? null : daysOff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.user_id
     *
     * @return the value of sign.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.user_id
     *
     * @param userId the value for sign.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}