package com.lintu.demo.mapper;

import com.lintu.demo.domain.Leave;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_leave
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_leave
     *
     * @mbggenerated
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_leave
     *
     * @mbggenerated
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_leave
     *
     * @mbggenerated
     */
    Leave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Leave record);
}