package com.lintu.demo.mapper;

import com.lintu.demo.domain.OverTime;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OverTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    int insert(OverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    int insertSelective(OverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    OverTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OverTime record);
}