package com.lintu.demo.mapper;

import com.lintu.demo.domain.RoleMenu;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_menu
     *
     * @mbggenerated
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_menu
     *
     * @mbggenerated
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_menu
     *
     * @mbggenerated
     */
    RoleMenu selectByPrimaryKey(Integer roleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleMenu record);
}