package com.lintu.demo.mapper;

import com.lintu.demo.domain.RoleUser;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_user
     *
     * @mbggenerated
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_user
     *
     * @mbggenerated
     */
    int insertSelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_user
     *
     * @mbggenerated
     */
    RoleUser selectByPrimaryKey(Integer roleUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_role_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleUser record);
}